-- AlterTable
ALTER TABLE "CycleTeam" ADD COLUMN "weightManager" DOUBLE PRECISION;
ALTER TABLE "CycleTeam" ADD COLUMN "weightPeer" DOUBLE PRECISION;
ALTER TABLE "CycleTeam" ADD COLUMN "weightDirectReport" DOUBLE PRECISION;
ALTER TABLE "CycleTeam" ADD COLUMN "weightSelf" DOUBLE PRECISION;
ALTER TABLE "CycleTeam" ADD COLUMN "weightExternal" DOUBLE PRECISION;
